
version: '3.7'

services:

  pgadmin:
    image: dpage/pgadmin4:2019-11-12-2
    ports:
      - '88:80'
    environment:
      PGADMIN_DEFAULT_EMAIL: jeanaime.ravomanana@gmail.com
      PGADMIN_DEFAULT_PASSWORD: P@ss!023
  db:
      image: postgres:11.5
      environment:
        POSTGRES_PASSWORD: w2f04naR2SUD17WGfo12cg==
        POSTGRES_DB: sapheer-account
        POSTGRES_USER: postgres
      ports:
        - '5432:5432'

volumes:
  spring_mvc: